package com.kgc.kgc_provider.mapper;

import com.kgc.kgc_provider.model.ItemKillSuccess;
import com.kgc.kgc_provider.model.ItemKillSuccessExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ItemKillSuccessMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_kill_success
     *
     * @mbg.generated
     */
    long countByExample(ItemKillSuccessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_kill_success
     *
     * @mbg.generated
     */
    int deleteByExample(ItemKillSuccessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_kill_success
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_kill_success
     *
     * @mbg.generated
     */
    int insert(ItemKillSuccess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_kill_success
     *
     * @mbg.generated
     */
    int insertSelective(ItemKillSuccess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_kill_success
     *
     * @mbg.generated
     */
    List<ItemKillSuccess> selectByExample(ItemKillSuccessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_kill_success
     *
     * @mbg.generated
     */
    ItemKillSuccess selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_kill_success
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ItemKillSuccess record, @Param("example") ItemKillSuccessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_kill_success
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ItemKillSuccess record, @Param("example") ItemKillSuccessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_kill_success
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ItemKillSuccess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_kill_success
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ItemKillSuccess record);
}