package com.kgc.kgc_provider.mapper;

import com.kgc.kgc_provider.model.WxuSer;
import com.kgc.kgc_provider.model.WxuSerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WxuSerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxuser
     *
     * @mbg.generated
     */
    long countByExample(WxuSerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxuser
     *
     * @mbg.generated
     */
    int deleteByExample(WxuSerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxuser
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxuser
     *
     * @mbg.generated
     */
    int insert(WxuSer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxuser
     *
     * @mbg.generated
     */
    int insertSelective(WxuSer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxuser
     *
     * @mbg.generated
     */
    List<WxuSer> selectByExample(WxuSerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxuser
     *
     * @mbg.generated
     */
    WxuSer selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxuser
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") WxuSer record, @Param("example") WxuSerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxuser
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") WxuSer record, @Param("example") WxuSerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxuser
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(WxuSer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxuser
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(WxuSer record);
    List<WxuSer> getAllUser(WxuSer wxuSer);
}