package com.kgc.kgc_provider.model;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table all_kind_user
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class AllKindUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column all_kind_user.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column all_kind_user.userName
     *
     * @mbg.generated
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column all_kind_user.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column all_kind_user.createTime
     *
     * @mbg.generated
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column all_kind_user.updateTime
     *
     * @mbg.generated
     */
    private Date updatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column all_kind_user.userLevel
     *
     * @mbg.generated
     */
    private Integer userlevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column all_kind_user.idDelete
     *
     * @mbg.generated
     */
    private Integer iddelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column all_kind_user.phone
     *
     * @mbg.generated
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column all_kind_user.openid
     *
     * @mbg.generated
     */
    private String openid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column all_kind_user.nickname
     *
     * @mbg.generated
     */
    private String nickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column all_kind_user.sex
     *
     * @mbg.generated
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column all_kind_user.language
     *
     * @mbg.generated
     */
    private String language;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column all_kind_user.city
     *
     * @mbg.generated
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column all_kind_user.province
     *
     * @mbg.generated
     */
    private String province;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column all_kind_user.country
     *
     * @mbg.generated
     */
    private String country;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column all_kind_user.headimgurl
     *
     * @mbg.generated
     */
    private String headimgurl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column all_kind_user.id
     *
     * @return the value of all_kind_user.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column all_kind_user.id
     *
     * @param id the value for all_kind_user.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column all_kind_user.userName
     *
     * @return the value of all_kind_user.userName
     *
     * @mbg.generated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column all_kind_user.userName
     *
     * @param username the value for all_kind_user.userName
     *
     * @mbg.generated
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column all_kind_user.password
     *
     * @return the value of all_kind_user.password
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column all_kind_user.password
     *
     * @param password the value for all_kind_user.password
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column all_kind_user.createTime
     *
     * @return the value of all_kind_user.createTime
     *
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column all_kind_user.createTime
     *
     * @param createtime the value for all_kind_user.createTime
     *
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column all_kind_user.updateTime
     *
     * @return the value of all_kind_user.updateTime
     *
     * @mbg.generated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column all_kind_user.updateTime
     *
     * @param updatetime the value for all_kind_user.updateTime
     *
     * @mbg.generated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column all_kind_user.userLevel
     *
     * @return the value of all_kind_user.userLevel
     *
     * @mbg.generated
     */
    public Integer getUserlevel() {
        return userlevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column all_kind_user.userLevel
     *
     * @param userlevel the value for all_kind_user.userLevel
     *
     * @mbg.generated
     */
    public void setUserlevel(Integer userlevel) {
        this.userlevel = userlevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column all_kind_user.idDelete
     *
     * @return the value of all_kind_user.idDelete
     *
     * @mbg.generated
     */
    public Integer getIddelete() {
        return iddelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column all_kind_user.idDelete
     *
     * @param iddelete the value for all_kind_user.idDelete
     *
     * @mbg.generated
     */
    public void setIddelete(Integer iddelete) {
        this.iddelete = iddelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column all_kind_user.phone
     *
     * @return the value of all_kind_user.phone
     *
     * @mbg.generated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column all_kind_user.phone
     *
     * @param phone the value for all_kind_user.phone
     *
     * @mbg.generated
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column all_kind_user.openid
     *
     * @return the value of all_kind_user.openid
     *
     * @mbg.generated
     */
    public String getOpenid() {
        return openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column all_kind_user.openid
     *
     * @param openid the value for all_kind_user.openid
     *
     * @mbg.generated
     */
    public void setOpenid(String openid) {
        this.openid = openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column all_kind_user.nickname
     *
     * @return the value of all_kind_user.nickname
     *
     * @mbg.generated
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column all_kind_user.nickname
     *
     * @param nickname the value for all_kind_user.nickname
     *
     * @mbg.generated
     */
    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column all_kind_user.sex
     *
     * @return the value of all_kind_user.sex
     *
     * @mbg.generated
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column all_kind_user.sex
     *
     * @param sex the value for all_kind_user.sex
     *
     * @mbg.generated
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column all_kind_user.language
     *
     * @return the value of all_kind_user.language
     *
     * @mbg.generated
     */
    public String getLanguage() {
        return language;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column all_kind_user.language
     *
     * @param language the value for all_kind_user.language
     *
     * @mbg.generated
     */
    public void setLanguage(String language) {
        this.language = language;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column all_kind_user.city
     *
     * @return the value of all_kind_user.city
     *
     * @mbg.generated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column all_kind_user.city
     *
     * @param city the value for all_kind_user.city
     *
     * @mbg.generated
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column all_kind_user.province
     *
     * @return the value of all_kind_user.province
     *
     * @mbg.generated
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column all_kind_user.province
     *
     * @param province the value for all_kind_user.province
     *
     * @mbg.generated
     */
    public void setProvince(String province) {
        this.province = province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column all_kind_user.country
     *
     * @return the value of all_kind_user.country
     *
     * @mbg.generated
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column all_kind_user.country
     *
     * @param country the value for all_kind_user.country
     *
     * @mbg.generated
     */
    public void setCountry(String country) {
        this.country = country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column all_kind_user.headimgurl
     *
     * @return the value of all_kind_user.headimgurl
     *
     * @mbg.generated
     */
    public String getHeadimgurl() {
        return headimgurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column all_kind_user.headimgurl
     *
     * @param headimgurl the value for all_kind_user.headimgurl
     *
     * @mbg.generated
     */
    public void setHeadimgurl(String headimgurl) {
        this.headimgurl = headimgurl;
    }
}