package com.kgc.kgc_provider.model;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table item
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class item implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   商品名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * Database Column Remarks:
     *   商品编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.code
     *
     * @mbg.generated
     */
    private String code;

    /**
     * Database Column Remarks:
     *   库存
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.stock
     *
     * @mbg.generated
     */
    private Long stock;

    /**
     * Database Column Remarks:
     *   采购时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.purchase_time
     *
     * @mbg.generated
     */
    private Date purchaseTime;

    /**
     * Database Column Remarks:
     *   是否有效（1=是；0=否）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.is_active
     *
     * @mbg.generated
     */
    private Integer isActive;
    private Date createTime;
    private Date updateTime;
    private Integer pSize;
    private Integer sPage;

    public Integer getpSize() {
        return pSize;
    }

    public void setpSize(Integer pSize) {
        this.pSize = pSize;
    }

    public Integer getsPage() {
        return sPage;
    }

    public void setsPage(Integer sPage) {
        this.sPage = sPage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.id
     *
     * @return the value of item.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.id
     *
     * @param id the value for item.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.name
     *
     * @return the value of item.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.name
     *
     * @param name the value for item.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.code
     *
     * @return the value of item.code
     *
     * @mbg.generated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.code
     *
     * @param code the value for item.code
     *
     * @mbg.generated
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.stock
     *
     * @return the value of item.stock
     *
     * @mbg.generated
     */
    public Long getStock() {
        return stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.stock
     *
     * @param stock the value for item.stock
     *
     * @mbg.generated
     */
    public void setStock(Long stock) {
        this.stock = stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.purchase_time
     *
     * @return the value of item.purchase_time
     *
     * @mbg.generated
     */
    public Date getPurchaseTime() {
        return purchaseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.purchase_time
     *
     * @param purchaseTime the value for item.purchase_time
     *
     * @mbg.generated
     */
    public void setPurchaseTime(Date purchaseTime) {
        this.purchaseTime = purchaseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.is_active
     *
     * @return the value of item.is_active
     *
     * @mbg.generated
     */
    public Integer getIsActive() {
        return isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.is_active
     *
     * @param isActive the value for item.is_active
     *
     * @mbg.generated
     */
    public void setIsActive(Integer isActive) {
        this.isActive = isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.create_time
     *
     * @return the value of item.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.create_time
     *
     * @param createTime the value for item.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.update_time
     *
     * @return the value of item.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.update_time
     *
     * @param updateTime the value for item.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}