package com.kgc.kgc_provider.model;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table item_kill_success
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class ItemKillSuccess implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_kill_success.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   秒杀成功生成的订单编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_kill_success.code
     *
     * @mbg.generated
     */
    private String code;

    /**
     * Database Column Remarks:
     *   商品id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_kill_success.item_id
     *
     * @mbg.generated
     */
    private Integer itemId;

    /**
     * Database Column Remarks:
     *   秒杀id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_kill_success.kill_id
     *
     * @mbg.generated
     */
    private Integer killId;

    /**
     * Database Column Remarks:
     *   用户id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_kill_success.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     * Database Column Remarks:
     *   秒杀结果: -1无效  0成功(未付款)  1已付款  2已取消
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_kill_success.status
     *
     * @mbg.generated
     */
    private Byte status;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_kill_success.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_kill_success.id
     *
     * @return the value of item_kill_success.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_kill_success.id
     *
     * @param id the value for item_kill_success.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_kill_success.code
     *
     * @return the value of item_kill_success.code
     *
     * @mbg.generated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_kill_success.code
     *
     * @param code the value for item_kill_success.code
     *
     * @mbg.generated
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_kill_success.item_id
     *
     * @return the value of item_kill_success.item_id
     *
     * @mbg.generated
     */
    public Integer getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_kill_success.item_id
     *
     * @param itemId the value for item_kill_success.item_id
     *
     * @mbg.generated
     */
    public void setItemId(Integer itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_kill_success.kill_id
     *
     * @return the value of item_kill_success.kill_id
     *
     * @mbg.generated
     */
    public Integer getKillId() {
        return killId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_kill_success.kill_id
     *
     * @param killId the value for item_kill_success.kill_id
     *
     * @mbg.generated
     */
    public void setKillId(Integer killId) {
        this.killId = killId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_kill_success.user_id
     *
     * @return the value of item_kill_success.user_id
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_kill_success.user_id
     *
     * @param userId the value for item_kill_success.user_id
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_kill_success.status
     *
     * @return the value of item_kill_success.status
     *
     * @mbg.generated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_kill_success.status
     *
     * @param status the value for item_kill_success.status
     *
     * @mbg.generated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_kill_success.create_time
     *
     * @return the value of item_kill_success.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_kill_success.create_time
     *
     * @param createTime the value for item_kill_success.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}